title: jverkamp.com
languageCode: en-us
baseURL: https://blog.jverkamp.com/
pygmentsCodeFences: true
pluralizelisttitles: false
enableEmoji: true

params:
    listTermsPerTaxonomy: 10
    disqusShortname: jverkamp
    disqusBaseURL: https://blog.jverkamp.com

rssLimit: 50
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "atom"

permalinks:
    photography: /:year/:month/:day/:title/
    programming: /:year/:month/:day/:title/
    research: /:year/:month/:day/:title/
    writing: /:year/:month/:day/:title/
    reviews: /:year/:month/:day/:title/
    other: /:year/:month/:day/:title/
    page: /:title/

taxonomies:
    series: series

    reviews/list: reviews/lists
    reviews/series: reviews/series

    photography/type: photography/types

    programming/language: programming/languages
    programming/source: programming/sources
    programming/topic: programming/topics

    writing/genre: writing/genres
    writing/type: writing/types
    writing/novel: writing/novels

# disqusShortname: "yourdiscussshortname"
