title: jverkamp.com
author: John-Paul Verkamp
url: http://localhost:8000
deploy-url: http://blog.jverkamp.com
deploy-repo: git@github.com:jpverkamp/jpverkamp.github.io.git

permalink: "{year}/{month}/{day}/{slug}"

atom-posts: 10

disqus-shortname: jverkamp
